name:  Check code coverage
on:
  pull_request:
    branches: [ master ]
jobs:
  code_coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Dart Stable
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: stable
      - name: Setup Flutter Stable
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      # - uses: subosito/flutter-action@master
      #  with:
      #    flutter-version: '1.22.5'
      #    channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info